name: Deploy

on:
  push:
    branches:
      - master
      - second

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: 'echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}'
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pvcy-challenge-runtime-${{ steps.vars.outputs.short_ref }}"
          heroku_email: "craig@bucketduck.com"